import path from 'path';
import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';

/**
 * T006: validates that a migration generated by `drizzle-kit generate` runs
 * successfully against a real SQLite database. Uses better-sqlite3 as a
 * same-SQL-dialect stand-in for expo-sqlite, since expo-sqlite's native
 * module cannot run under Jest (see docs/TEST_STRATEGY.md).
 */
describe('drizzle + SQLite migration toolchain', () => {
  it('creates the throwaway toolchain_check table from the generated migration', () => {
    const sqlite = new Database(':memory:');
    const db = drizzle(sqlite);

    migrate(db, {
      migrationsFolder: path.join(__dirname, '../../../../migrations'),
    });

    const tables = sqlite
      .prepare(
        "SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'toolchain_check'",
      )
      .all();

    expect(tables).toHaveLength(1);

    sqlite.close();
  });
});
